-- ============================================================================
-- CityGuide — PostgreSQL / Supabase schema (migration 001)
-- ----------------------------------------------------------------------------
-- Logically identical to ../sqlite/001_init.sql. Used when DATABASE_URL points
-- at a PostgreSQL instance (including Supabase).
--
-- Supabase note: this application performs all data access through its own
-- Express API using the direct PostgreSQL connection, so every table is owned
-- by the API's database role. Row Level Security is still enabled and locked
-- down at the end of this file so that the auto-generated Supabase anon and
-- authenticated API roles can never read or write these tables directly.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT        NOT NULL,
  email         TEXT        NOT NULL,
  password_hash TEXT        NOT NULL,
  role          TEXT        NOT NULL DEFAULT 'traveler'
                            CHECK (role IN ('traveler', 'curator', 'admin')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT users_email_unique UNIQUE (email)
);

-- ---------------------------------------------------------------------------
-- sessions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sessions (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_hash  TEXT        NOT NULL,
  user_id     INTEGER     NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  user_agent  TEXT,
  ip_address  TEXT,
  expires_at  TIMESTAMPTZ NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT sessions_token_hash_unique UNIQUE (token_hash)
);

-- ---------------------------------------------------------------------------
-- categories
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS categories (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT        NOT NULL,
  slug        TEXT        NOT NULL,
  description TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT categories_name_unique UNIQUE (name),
  CONSTRAINT categories_slug_unique UNIQUE (slug)
);

-- ---------------------------------------------------------------------------
-- attractions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS attractions (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT        NOT NULL,
  description TEXT        NOT NULL,
  category_id INTEGER     NOT NULL REFERENCES categories (id) ON DELETE RESTRICT,
  address     TEXT        NOT NULL,
  latitude    DOUBLE PRECISION
              CHECK (latitude  IS NULL OR (latitude  BETWEEN -90  AND 90)),
  longitude   DOUBLE PRECISION
              CHECK (longitude IS NULL OR (longitude BETWEEN -180 AND 180)),
  image_url   TEXT,
  created_by  INTEGER REFERENCES users (id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- saved_places — business rule: one save per (user, attraction)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS saved_places (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       INTEGER     NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  attraction_id INTEGER     NOT NULL REFERENCES attractions (id) ON DELETE CASCADE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT saved_places_user_attraction_unique UNIQUE (user_id, attraction_id)
);

-- ---------------------------------------------------------------------------
-- itineraries
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS itineraries (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER     NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  name        TEXT        NOT NULL,
  description TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- itinerary_items — business rules: no duplicate stop, no duplicate slot
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS itinerary_items (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  itinerary_id  INTEGER     NOT NULL REFERENCES itineraries (id) ON DELETE CASCADE,
  attraction_id INTEGER     NOT NULL REFERENCES attractions (id) ON DELETE CASCADE,
  position      INTEGER     NOT NULL CHECK (position >= 0),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT itinerary_items_itinerary_attraction_unique UNIQUE (itinerary_id, attraction_id),
  CONSTRAINT itinerary_items_itinerary_position_unique   UNIQUE (itinerary_id, position)
);

-- ---------------------------------------------------------------------------
-- audit_logs
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_logs (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER REFERENCES users (id) ON DELETE SET NULL,
  action      TEXT        NOT NULL,
  entity_type TEXT        NOT NULL,
  entity_id   TEXT,
  metadata    JSONB,
  ip_address  TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- geocode_cache
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS geocode_cache (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  query_key    TEXT        NOT NULL,
  query        TEXT        NOT NULL,
  display_name TEXT,
  latitude     DOUBLE PRECISION,
  longitude    DOUBLE PRECISION,
  payload      JSONB,
  provider     TEXT        NOT NULL DEFAULT 'nominatim',
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT geocode_cache_query_key_unique UNIQUE (query_key)
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_sessions_user_id        ON sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires_at     ON sessions (expires_at);
CREATE INDEX IF NOT EXISTS idx_attractions_category    ON attractions (category_id);
CREATE INDEX IF NOT EXISTS idx_attractions_name        ON attractions (name);
CREATE INDEX IF NOT EXISTS idx_attractions_created_by  ON attractions (created_by);
CREATE INDEX IF NOT EXISTS idx_saved_places_user       ON saved_places (user_id);
CREATE INDEX IF NOT EXISTS idx_saved_places_attraction ON saved_places (attraction_id);
CREATE INDEX IF NOT EXISTS idx_itineraries_user        ON itineraries (user_id);
CREATE INDEX IF NOT EXISTS idx_itinerary_items_order   ON itinerary_items (itinerary_id, position);
CREATE INDEX IF NOT EXISTS idx_itinerary_items_attr    ON itinerary_items (attraction_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at   ON audit_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user         ON audit_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity       ON audit_logs (entity_type, entity_id);

-- ---------------------------------------------------------------------------
-- Supabase hardening
-- ----------------------------------------------------------------------------
-- All access goes through the Express API over the direct Postgres connection.
--
-- RLS is enabled on every application table, including schema_migrations (which
-- the migration runner creates before this file is applied). Enabling RLS with
-- no matching policy is already deny-by-default for every role except the table
-- owner, so the tables are protected even on a plain PostgreSQL server where
-- Supabase's `anon` and `authenticated` roles do not exist.
--
-- On Supabase those roles *do* exist, so explicit deny policies are installed as
-- well — making the intent legible to anyone reading the schema and immune to a
-- future default-privilege change.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  tbl TEXT;
  api_roles TEXT[] := ARRAY['anon', 'authenticated'];
  r TEXT;
BEGIN
  FOREACH tbl IN ARRAY ARRAY[
    'users', 'sessions', 'categories', 'attractions',
    'saved_places', 'itineraries', 'itinerary_items',
    'audit_logs', 'geocode_cache', 'schema_migrations'
  ]
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', tbl);

    FOREACH r IN ARRAY api_roles
    LOOP
      -- Create the role if Supabase provisioned it; ignore when absent.
      IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
        EXECUTE format('DROP POLICY IF EXISTS %I ON %I', 'deny_' || r || '_' || tbl, tbl);
        EXECUTE format(
          'CREATE POLICY %I ON %I FOR ALL TO %I USING (false) WITH CHECK (false)',
          'deny_' || r || '_' || tbl, tbl, r
        );
      END IF;
    END LOOP;
  END LOOP;
END $$;
